chore: configure integration test workflow
ExpediaGroup/xap-java-sdk pull request #30
Opened 2024-11-21 08:49 UTC by Simon-Wong-hjz

# Situation

# Task

# Action

# Testing

# Results

# Notes

2024-11-21 13:43 UTC, mohnoor94 approved these changes

2024-11-21 13:43 UTC, mohnoor94 requested changes
Please fill the PR template.

2024-12-10 15:05 UTC, mohnoor94 approved these changes

2024-12-16 09:17 UTC, anssari1 approved these changes

2024-12-16 09:17 UTC, merged